import { build } from "vite";
import react from "@vitejs/plugin-react";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
await build({ configFile: false, root, plugins: [react()], resolve: { alias: { "@": root } }, build: {
  outDir: ".mcp-app-build", emptyOutDir: true, cssCodeSplit: false,
  lib: { entry: `${root}mcp-app/main.tsx`, name: "Agen8Graph", formats: ["iife"], fileName: () => "graph.js" },
} });
const js = await readFile(`${root}.mcp-app-build/graph.js`, "utf8"), css = await readFile(`${root}.mcp-app-build/agen8-site.css`, "utf8");
const icon = `data:image/svg+xml;base64,${Buffer.from(await readFile(`${root}public/favicon.svg`, "utf8")).toString("base64")}`;
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agen8 work graph</title><style>${css.replace(/<\/style/gi, "<\\/style")}</style></head><body><div id="root"></div><script>${js.replace(/<\/script/gi, "<\\/script")}</script></body></html>`;
await mkdir(`${root}lib/generated`, { recursive: true });
await writeFile(`${root}lib/generated/graph-app.ts`, `// Generated by build-mcp-app.mjs.\nexport const graphHtml = ${JSON.stringify(html)};\nexport const graphIcon = ${JSON.stringify(icon)};\n`);
await writeFile(`${root}.mcp-app-build/graph.html`, html);
console.log(`Self-contained graph app: ${Buffer.byteLength(html).toLocaleString()} bytes`);
