#!/usr/bin/env bash
set -euo pipefail
#
# Example: Daily report automation
#
# Demonstrates a complete automated workflow that:
# 1. Collects data from various sources
# 2. Generates a summary report
# 3. Saves to a date-stamped file
#
# Usage:
#   ./daily_report.sh                              # generate today's report
#   ./daily_report.sh --output /path/to/reports    # custom output directory
#   ./daily_report.sh --dry-run                    # preview without writing
#
# Designed as a template — customize the data collection steps for your needs.
# Schedule with: cron_setup.sh --add "0 9 * * 1-5" "./daily_report.sh" --name daily-report

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="${HOME}/reports"
DRY_RUN=false
TODAY=$(date +%Y-%m-%d)
REPORT_FILE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)  OUTPUT_DIR="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help) echo "Usage: $0 [--output DIR] [--dry-run]"; exit 0 ;;
        *) shift ;;
    esac
done

REPORT_FILE="${OUTPUT_DIR}/daily_report_${TODAY}.md"

log() {
    echo "[$(date +%H:%M:%S)] $*" >&2
}

# --- Step 1: System Info ------------------------------------------------------
log "Collecting system info..."

HOSTNAME=$(hostname)
UPTIME=$(uptime | sed 's/^.*up /up /' | sed 's/,.*load/ load/')
DISK_USAGE=$(df -h / | tail -1 | awk '{print $5}')
MEM_INFO=""
if command -v vm_stat &>/dev/null; then
    PAGES_FREE=$(vm_stat | grep "Pages free" | awk '{print $3}' | tr -d '.')
    MEM_INFO="pages_free: ${PAGES_FREE}"
elif command -v free &>/dev/null; then
    MEM_INFO=$(free -h | grep Mem | awk '{print "used:", $3, "/", $2}')
fi

# --- Step 2: Git Status (if in a repo) ---------------------------------------
log "Checking git status..."

GIT_SECTION=""
if git rev-parse --is-inside-work-tree &>/dev/null; then
    REPO_NAME=$(basename "$(git rev-parse --show-toplevel)")
    BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
    COMMITS_TODAY=$(git log --oneline --since="${TODAY}" 2>/dev/null | wc -l | tr -d ' ')
    UNCOMMITTED=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    GIT_SECTION="
## Repository: ${REPO_NAME}
- **Branch:** ${BRANCH}
- **Commits today:** ${COMMITS_TODAY}
- **Uncommitted changes:** ${UNCOMMITTED}
"
fi

# --- Step 3: Running Processes ------------------------------------------------
log "Checking processes..."

PROCESS_COUNT=$(ps aux | wc -l | tr -d ' ')
TOP_PROCESSES=$(ps aux --sort=-%cpu 2>/dev/null | head -6 || ps aux | head -6)

# --- Step 4: Generate Report --------------------------------------------------
log "Generating report..."

REPORT="# Daily Report — ${TODAY}

**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Host:** ${HOSTNAME}

## System Status
| Metric | Value |
|--------|-------|
| Uptime | ${UPTIME} |
| Disk Usage (/) | ${DISK_USAGE} |
| Memory | ${MEM_INFO} |
| Processes | ${PROCESS_COUNT} |
${GIT_SECTION}
## Top Processes
\`\`\`
${TOP_PROCESSES}
\`\`\`

## Notes
- *Add your own data collection steps above*
- *Customize this template for your workflow*

---
*Generated by agen8 automation skill*
"

# --- Step 5: Output -----------------------------------------------------------
if [ "$DRY_RUN" = true ]; then
    echo "$REPORT"
    log "Dry run complete — no file written."
else
    mkdir -p "$OUTPUT_DIR"
    echo "$REPORT" > "$REPORT_FILE"
    log "Report saved to: ${REPORT_FILE}"
    echo "{\"status\": \"ok\", \"output\": \"${REPORT_FILE}\", \"date\": \"${TODAY}\"}"
fi
